#!/usr/bin/env python3
import inspect
from types import CoroutineType

import asyncio
from typing import TypedDict
import time
import psycopg
from ..utils.conn_factory import conn_factory
import threading
import ast

class SysState(TypedDict):
    conn: psycopg.Connection


ALLOWED_NODES = (ast.FunctionDef,
                 ast.Call,
                 ast.Assign,
                 ast.Add,
                 ast.And,
                 ast.Assert,
                 ast.Break,
                 ast.Compare,
                 ast.Expression,
                 ast.For,
                 ast.Continue,
                 ast.While,
                 ast.Yield,
                 ast.Match,
                 ast.Not)
ALLOWED_FUNCTIONS = ("print", "")
# NOTE: This is for later, for validation of what AI typed in there. 
# NOTE: I still think DSL is a good idea, because like, why not?

def setup():
    threading.Thread(target=cronjob_executor, daemon=True).start()

def cronjob_executor():
    conn = conn_factory()
    
    cronjob_conn = conn_factory()
    notifies_conn = conn_factory()

    notifies_conn.execute("LISTEN 'cronjob_changes'")

    cronjob_changed = threading.Event()

    def cronjob_changes_listener(conn: psycopg.Connection):
        for n in conn.notifies():
            cronjob_changed.set()

    threading.Thread(target=cronjob_changes_listener, args=(notifies_conn,), daemon=True).start()

    loop = asyncio.new_event_loop()

    while True:
        sys_state: SysState = {
            "conn": cronjob_conn
        }

        cronjob_fetch = conn.execute("""
    SELECT addr, body, run_at, type FROM cronjobs_to_run LIMIT 1
                     """).fetchone() # cronjobs_to_run is a view, wich includes order ba ASC.

        if cronjob_fetch is None:
            cronjob_changed.wait()
            continue

        wait_time = cronjob_fetch[2] - time.time() # RUN AT IS EPOCH
        changed_flag = cronjob_changed.wait(wait_time if wait_time > 0 else 0.001)

        if changed_flag:
            cronjob_changed.clear()
            continue

        try:
            exec(cronjob_fetch[1]) # Do you have a better solution? Propse a better solution if you want. 
            # I need to execute a cronjob stored in postgres. 
            if "cronjob_function" not in locals():
                raise NameError("Cronjob function not in locals")

            if inspect.iscoroutinefunction(cronjob_function):
                loop.run_until_complete(cronjob_function(sys_state))
            else:
                cronjob_function(sys_state)
            # NOTE: IGNORE BECAUSE THIS FUNCTION WILL APPEAR AFTER EXEC, and also any error will be just logged, the cronjob no more executed, and we move on.
        except Exception as e:
            match cronjob_fetch[3]:
                case "cronjob_once":
                    conn.execute("""
            UPDATE cronjob_once SET error = TRUE, error_text = %s WHERE addr = %s;
                                 """, (str(e), cronjob_fetch[0]))
                case "cronjob_loop":
                     conn.execute("""
            UPDATE cronjob_loop SET error = TRUE, error_text = %s WHERE addr = %s;
                                  """, (str(e), cronjob_fetch[0]))
                case _:
                     raise psycopg.DatabaseError(f"unexpected type. Type got {cronjob_fetch[3]}, expected cronjob_once OR cronjob_loop")
                # NOTE: this is not misleading, because the type is autogenerated at the database side, and if its wrong, its actually Database error.
        else:
            match cronjob_fetch[3]:
                case "cronjob_once":
                    conn.execute("""
            UPDATE cronjob_once SET finished = TRUE WHERE addr = %s;
                                 """, (cronjob_fetch[0], ))
                case "cronjob_loop":
                     conn.execute("""
            UPDATE cronjob_loop SET last_ran = %s WHERE addr = %s;
                                  """, (time.time(), cronjob_fetch[0]))
                case _:
                     raise psycopg.DatabaseError(f"unexpected type. Type got {cronjob_fetch[3]}, expected cronjob_once OR cronjob_loop")
                # NOTE: this is not misleading, because the type is autogenerated at the database side, and if its wrong, its actually Database error.
