#!/usr/bin/env python3
import asyncio
from typing import TypedDict
import time
import psycopg
from ..utils.conn_factory import conn_factory
import threading

class SysState(TypedDict):
    conn: psycopg.Connection

def setup():
    conn = conn_factory()
    threading.Thread(target=cronjob_executor, daemon=True).start()

def cronjob_executor():
    conn = conn_factory()
    conn.execute("LISTEN 'cronjob_changes'")

    cronjob_conn = conn_factory()

    cronjob_changed = threading.Event()

    def cronjob_changes_listener(conn: psycopg.Connection):
        for n in conn.notifies():
            cronjob_changed.set()

    threading.Thread(target=cronjob_changes_listener, args=(conn,), daemon=True).start()

    while True:
        sys_state: SysState = {
            "conn": cronjob_conn
        }

        cronjob_fetch = conn.execute("""
    SELECT addr, body, run_at, type FROM cronjobs_to_run LIMIT 1
                     """).fetchone()

        if cronjob_fetch is None:
            cronjob_changed.wait()
            continue

        exec(cronjob_fetch[1]) # Do you have a better solution? Propse a better solution if you want. 
        # I need to execute a cronjob stored in postgres. 

        changed_flag = cronjob_changed.wait(time.time() - cronjob_fetch[2])

        if changed_flag:
            cronjob_changed.clear()
            continue

        try:
            if isinstance(cronjob_function, CoroutineType): # pyright: ignore
                asyncio.run(cronjob_function(sys_state)) # pyright: ignore
            else:
                cronjob_function(sys_state) # pyright: ignore
            # NOTE: IGNORE BECAUSE THIS FUNCTION WILL APPEAR AFTER EXEC, and also any error will be just logged, the cronjob no more executed, and we move on.
        except Exception as e:
            match cronjob_fetch[3]:
                case "cronjob_once":
                    conn.execute("""
            UPDATE cronjob_once SET error = TRUE, error_text = %s WHERE addr = %s;
                                 """, (str(e), cronjob_fetch[0]))
                case "cronjob_loop":
                     conn.execute("""
            UPDATE cronjob_loop SET error = TRUE, error_text = %s WHERE addr = %s;
                                  """, (str(e), cronjob_fetch[0]))
                case _:
                     raise psycopg.DatabaseError(f"unexpected type. Type got {cronjob_fetch[3]}, expected cronjob_once OR cronjob_loop")
                # NOTE: this is not misleading, because the type is autogenerated at the database side, and if its wrong, its actually Database error.
